{{cookiecutter.project_slug}}/apps/homepage/urls.py
from django.conf.urls import url 
 
from . import views 
 
urlpatterns = [ 
    url( 
        regex=r'^$', 
        view=views.HomeView, 
        name='home' 
    ), 
] 

{{cookiecutter.project_slug}}/apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^login/$', 
        view=views.login, 
        name='account_login' 
    ), 
    url( 
        regex=r'^logout/$', 
        view=views.logout, 
        name='account_logout' 
    ), 
    url( 
        regex=r'^signup/$', 
        view=views.signup, 
        name='account_signup' 
    ), 
    url( 
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

{{cookiecutter.project_slug}}/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static 
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [

    # Multilingual
    url(r'^i18n/', include('django.conf.urls.i18n')),


    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(settings.ADMIN_URL, admin.site.urls),
 
    # Your stuff: custom urls includes go here 
 
 
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

urlpatterns += i18n_patterns(

    # Homepage app
    url(r'^', include('homepage.urls')),  

    # User management
    url(r'^users/', include('users.urls', namespace='users')), 
    url(r'^accounts/', include('allauth.urls')), 

    # User avatar 
    url(r'^avatar/', include('avatar.urls')), 
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

{{cookiecutter.project_slug}}/apps/homepage/models.py
from django.db import models 
 
# Create your models here. 

{{cookiecutter.project_slug}}/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

{{cookiecutter.project_slug}}/apps/homepage/views.py
from django.shortcuts import render 
 
def HomeView(request): 
    """ 
    """ 
 
    context = {} 
    return render(request, 'homepage/home.html', context)

{{cookiecutter.project_slug}}/apps/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from allauth.account.views import LoginView, LogoutView, SignupView 

from .models import User


class UserLoginView(LoginView): 
    template_name = 'users/login.html' 
 
login = UserLoginView.as_view() 

 
class UserLogoutView(LogoutView): 
    template_name = "users/logout.html" 
 
logout = UserLogoutView.as_view() 
 
 
class UserSignupView(SignupView): 
    template_name = "users/signup.html" 
 
signup = UserSignupView.as_view() 


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

{{cookiecutter.project_slug}}/apps/homepage/templates/homepage/home.html
{% raw %}{% extends "base.html" %}

<h1> Homepage </h1>
{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/avatar/add.html
{% raw %}{% extends "base.html" %}
{% load i18n avatar_tags %}

{% block content %}
    <p>{% trans "Your current avatar: " %}</p>
    {% avatar user %}
    {% if not avatars %}
        <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
    {% endif %}
    <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
        {{ upload_avatar_form.as_p }}
        <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
    </form>
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/avatar/change.html
{% raw %}{% extends "base.html" %}
{% load i18n avatar_tags %}

{% block content %}
    <p>{% trans "Your current avatar: " %}</p>
    {% avatar user %}
    {% if not avatars %}
        <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
    {% else %}
        <form method="POST" action="{% url 'avatar_change' %}">
            <ul>
                {{ primary_avatar_form.as_ul }}
            </ul>
            <p>{% csrf_token %}<input type="submit" value="{% trans "Choose new Default" %}" /></p>
        </form>
    {% endif %}
    <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
        {{ upload_avatar_form.as_p }}
        <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
    </form>
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/avatar/confirm_delete.html
{% raw %}{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <p>{% trans "Please select the avatars that you would like to delete." %}</p>
    {% if not avatars %}
        {% url 'avatar_change' as avatar_change_url %}
        <p>{% blocktrans %}You have no avatars to delete. Please <a href="{{ avatar_change_url }}">upload one</a> now.{% endblocktrans %}</p>
    {% else %}
        <form method="POST" action="{% url 'avatar_delete' %}">
            <ul>
                {{ delete_avatar_form.as_ul }}
            </ul>
            <p>{% csrf_token %}<input type="submit" value="{% trans "Delete These" %}" /></p>
        </form>
    {% endif %}
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/login.html
{% raw %}{% extends "base.html" %} 
{% load i18n %} 
{% load crispy_forms_tags %} 
 
{% block head_title %}{% trans "Sign In" %}{% endblock %} 
 
{% block heading %} 
  <h2>{% trans "Sign In" %}</h2> 
{% endblock %} 
 
{% block content %} 
 
  <p>{% blocktrans %}If you have not created an account yet, then please 
  <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p> 
 
  <form action="{% url "users:account_login" %}" method="post" accept-charset="utf-8"> 
    {{ form|crispy }} 
    {% csrf_token %} 
    <input type="hidden" name="next" value="{{ next }}"> 
    <input class="btn btn-default" type="submit" value={% trans "Sign In" %}> 
    <br> 
    <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a> 
  </form> 
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/logout.html
{% raw %}{% extends "base.html" %} 
{% load i18n %} 
{% load crispy_forms_tags %} 
 
{% block head_title %}{% trans "Sign Out" %}{% endblock %} 
 
{% block heading %} 
  <h2>{% trans "Sign Out" %}</h2> 
{% endblock %} 
 
{% block content %} 
 
  <p>{% trans 'Are you sure you want to sign out?' %}</p> 
 
  <form method="post" action="{% url 'users:account_logout' %}"> 
    {{ form|crispy }} 
    {% csrf_token %} 
    <button type="submit">{% trans 'Sign Out' %}</button> 
  </form> 
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/signup.html
{% raw %}{% extends "base.html" %} 
{% load i18n %} 
{% load crispy_forms_tags %} 
 
{% block head_title %}{% trans "Signup" %}{% endblock %} 
 
{% block heading %} 
  <h2>{% trans "Signup" %}</h2> 
{% endblock %} 
 
{% block content %} 
 
  <p>{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p> 
 
  <form action="{% url "users:account_signup" %}" method="post" accept-charset="utf-8"> 
    {{ form|crispy }} 
    {% csrf_token %} 
    <input type="hidden" name="next" value="{{ next }}"> 
    <input class="btn btn-default" type="submit" value={% trans "Sign Up" %}> 
  </form> 
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/user_detail.html
{% raw %}{% extends "base.html" %}
{% load static %}
{% load avatar_tags %} 


{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-4"> 
      <a href="{% url 'avatar_change' %}">{% avatar user %}</a> 
    </div> 
    <div class="col-sm-8"> 
      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/user_form.html
{% raw %}{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/apps/users/templates/users/user_list.html
{% raw %}{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/base.html
{% raw %}{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="{% block description %}{% endblock description %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}" />
    <meta name="viewport" content="{% block viewport %}width=device-width{% endblock viewport %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}{% endraw %}{{cookiecutter.project_name}}{% raw %}{% endblock title %}</title>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/gif" href="{% static 'img/favicon.gif' %}">

    {% block css %}
    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

      {% block css-app %}
      <!-- CSS section for apps -->
      {% endblock css-app %}

    {% endblock css%}

  </head>

  <body>

    {% block navbar %}
    <!-- top navbar -->
    {% include "component/navbar.html" %}    
    {% endblock navbar %}

    {% block content %}
    <div class="container">
        <p>Use this document as a way to quick start any new project.</p>
    </div> <!-- /container -->
    {% endblock content %}

    {% block footer %}
    <!-- footer -->
    {% include "component/footer.html" %}    
    {% endblock footer %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/scripts.js' %}"></script>

      {% block javascript-app %}
      <!-- JavaScript section for apps -->
      {% endblock javascript-app %}

    {% endblock javascript %}
  </body>
</html>{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/component/footer.html
<footer>
Built with <a href="https://www.manaxproject.com/" target="_blank">manax</a>
</footer>

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/component/navbar.html
{% raw %}{% load i18n %}
{% load avatar_tags %} 
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">{% endraw %}{{ cookiecutter.project_name }}{% raw %}</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      {% block innavbar %}

      {% endblock innavbar %}


      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">{% trans "Notifications" %}</a> 
        </li> 
        <li class="nav-item"> 
          <!--<a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>-->
          <div class="dropdown"> 
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuUserProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"> 
              {% avatar user 45 class="img-circle img-responsive img-thumbnail" id="user_avatar" %} 
            <span class="caret"></span>
            </button> 
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuUserProfile"> 
              <li><a href="#">Action</a></li> 
              <li><a href="#">Another action</a></li> 
              <li><a href="#">Something else here</a></li> 
              <li role="separator" class="divider"></li> 
              <li><a href="#">Separated link</a></li> 
            </ul> 
          </div> 
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
        </li>
        <li class="nav-item">
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
        </li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/component/ribbon.html
<style type="text/css"> 
*{
  margin: 0;
  padding: 0;
}

/* The ribbons */

.corner-ribbon{
  width: 200px;
  background: #e43;
  position: absolute;
  top: 25px;
  left: -50px;
  text-align: center;
  line-height: 50px;
  letter-spacing: 1px;
  color: #f0f0f0;
  transform: rotate(-45deg);
  -webkit-transform: rotate(-45deg);
}

/* Custom styles */

.corner-ribbon.sticky{
  position: fixed;
}

.corner-ribbon.shadow{
  box-shadow: 0 0 3px rgba(0,0,0,.3);
}

/* Different positions */

.corner-ribbon.top-left{
  top: 25px;
  left: -50px;
  transform: rotate(-45deg);
  -webkit-transform: rotate(-45deg);
}

.corner-ribbon.top-right{
  top: 25px;
  right: -50px;
  left: auto;
  transform: rotate(45deg);
  -webkit-transform: rotate(45deg);
}

.corner-ribbon.bottom-left{
  top: auto;
  bottom: 25px;
  left: -50px;
  transform: rotate(45deg);
  -webkit-transform: rotate(45deg);
}

.corner-ribbon.bottom-right{
  top: auto;
  right: -50px;
  bottom: 25px;
  left: auto;
  transform: rotate(-45deg);
  -webkit-transform: rotate(-45deg);
}

/* Colors */

.corner-ribbon.white{background: #f0f0f0; color: #555;}
.corner-ribbon.black{background: #333;}
.corner-ribbon.grey{background: #999;}
.corner-ribbon.blue{background: #39d;}
.corner-ribbon.green{background: #2c7;}
.corner-ribbon.turquoise{background: #1b9;}
.corner-ribbon.purple{background: #95b;}
.corner-ribbon.red{background: #e43;}
.corner-ribbon.orange{background: #e82;}
.corner-ribbon.yellow{background: #ec0;}
</style>

<div class="corner-ribbon top-left sticky red shadow">Hello</div>
<div class="corner-ribbon top-right sticky blue">Hello</div>
<div class="corner-ribbon bottom-left sticky orange">Hello</div>
<div class="corner-ribbon bottom-right sticky green shadow">Hello</div>

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/pages/about.html
{% raw %}{% extends "base.html" %}{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/pages/home.html
{% raw %}{% extends "base.html" %}{% endraw %}